apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow
on:
  push:
    branches:
      - "**"
jobs:
  install:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - uses: docker://cypress/browsers:node16.16.0-chrome105-ff104-edge
        run: |
          yarn install
          yarn types
          yarn lint
          yarn test:unit:ci
          yarn build:ci
